version: "3"
services:
  nginx:
    build: ./deploy/nginx
    container_name: 'content-service-nginx'
    volumes:
      - content-service-storage:/var/content-service-storage/
    networks: 
      - marketing-network
      - content-service-network
  content-service:
    env_file: .env
    build: .
    volumes:
      - content-service-storage:/app/content-service-storage/
    networks: 
      - content-service-network
    deploy:
      replicas: 3

networks:
  marketing-network:
    name: marketing-network
  content-service-network:
    name: content-service-network

volumes: 
  content-service-storage: {}





